  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write
    issues: write
    repository-projects: write
    
  jobs:
    build-linux:
      name: Build for Linux
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
  
        - name: Install dependencies
          run: npm install
  
        - name: Build Linux package
          run: yarn forge:make --platform=linux
  
        - name: Upload Linux package
          uses: actions/upload-artifact@v3
          with:
            name: linux-package
            path: out/make
            
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: setup-node
            uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "Myros27" && git config user.email "Myros27@users.noreply.github.com"
          - name: Deploy
            run: npm run deploy
